# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='_menu_items_+', to='test_assignment_app.Menu'),
        ),
    ]
