# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_assignment_app', '0002_auto_20161017_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='_menu_items_+', to='test_assignment_app.Menu'),
        ),
    ]
