# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_assignment_app', '0004_auto_20161017_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='test_assignment_app.Menu'),
        ),
    ]
